name: VendralyCore
main: com.vendraly.VendralyCore
version: 1.0.0
api-version: '1.21'
author: Vendraly
commands:
  login:
    description: Inicia sesión
  register:
    description: Registra un nuevo jugador
  eco:
    description: Administra la economía
    permission: vendraly.economy.admin
  pay:
    description: Transfiere efectivo a otro jugador
  trade:
    description: Sistema de comercio seguro
  clan:
    description: Gestiona clanes
  jobs:
    description: Información de oficios
  role:
    description: Cambia roles de jugadores
    permission: vendraly.roles
  stats:
    description: Gestiona estadísticas RPG
  loot:
    description: Lista tablas de loot
  rgpexp:
    description: Otorga experiencia RPG
permissions:
  vendraly.economy.admin:
    description: Gestionar economía
    default: op
  vendraly.roles:
    description: Gestionar roles
    default: op
  vendraly.rpg.exp:
    description: Dar experiencia RPG
    default: op
